"""add engagement metrics columns to source_posts

Revision ID: 53dc8359af01
Revises: ed98306ffb75
Create Date: 2026-08-04 15:53:54.542549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dc8359af01'
down_revision: Union[str, Sequence[str], None] = 'ed98306ffb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_posts', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('source_posts', sa.Column('retweet_count', sa.Integer(), nullable=True))
    op.add_column('source_posts', sa.Column('reply_count', sa.Integer(), nullable=True))
    op.add_column('source_posts', sa.Column('quote_count', sa.Integer(), nullable=True))
    op.add_column('source_posts', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_posts', 'view_count')
    op.drop_column('source_posts', 'quote_count')
    op.drop_column('source_posts', 'reply_count')
    op.drop_column('source_posts', 'retweet_count')
    op.drop_column('source_posts', 'like_count')
    # ### end Alembic commands ###
