"""initial schema: users, topics, baseline snapshots, digests, digest topic results, source posts, themes, draft posts, posting modes

Revision ID: 5a8feb84f7fc
Revises: 
Create Date: 2026-07-21 20:13:28.196609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8feb84f7fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('x_account_handle', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('digests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('run_type', sa.Enum('SCHEDULED', 'ON_DEMAND', name='digestruntype'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'PARTIAL', 'FAILED', name='digeststatus'), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posting_modes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('MANUAL', 'AUTONOMOUS', name='postingmodevalue'), nullable=False),
    sa.Column('confidence_threshold', sa.Integer(), nullable=False),
    sa.Column('validation_period_ends_at', sa.DateTime(), nullable=False),
    sa.Column('kill_switch_engaged', sa.Boolean(), nullable=False),
    sa.Column('last_post_published_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x_handles', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REMOVED', name='topicstatus'), nullable=False),
    sa.Column('first_tracked_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_topic_user_name_active', 'topics', ['user_id', 'name'], unique=True, sqlite_where=sa.text("status = 'active'"))
    op.create_table('digest_topic_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('digest_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.Enum('THEMES_PRESENT', 'NO_SIGNIFICANT_ACTIVITY', 'ALL_FILTERED_AS_NOISE', 'FETCH_ERROR', 'INCOMPLETE_RATE_LIMITED', name='digesttopicoutcome'), nullable=False),
    sa.Column('error_detail', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['digest_id'], ['digests.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_baseline_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('window_date', sa.Date(), nullable=False),
    sa.Column('filtered_post_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'window_date', name='uq_baseline_topic_window_date')
    )
    op.create_table('themes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('digest_topic_result_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('is_spike', sa.Boolean(), nullable=False),
    sa.Column('spike_ratio', sa.Numeric(), nullable=True),
    sa.Column('cluster_post_count', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['digest_topic_result_id'], ['digest_topic_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('theme_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('draft_text', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HELD_MANUAL', 'PUBLISHED_MANUAL', 'HELD_BELOW_THRESHOLD', 'PUBLISHED_AUTO', 'PUBLISH_FAILED', name='draftpoststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('publish_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('digest_topic_result_id', sa.Uuid(), nullable=False),
    sa.Column('x_post_id', sa.String(), nullable=False),
    sa.Column('author_handle', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('filter_outcome', sa.Enum('KEPT', 'EXCLUDED_RULE', 'EXCLUDED_DEEPER_CHECK', name='filteroutcome'), nullable=False),
    sa.Column('theme_id', sa.Uuid(), nullable=True),
    sa.Column('is_example', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['digest_topic_result_id'], ['digest_topic_results.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_posts')
    op.drop_table('draft_posts')
    op.drop_table('themes')
    op.drop_table('topic_baseline_snapshots')
    op.drop_table('digest_topic_results')
    op.drop_index('uq_topic_user_name_active', table_name='topics', sqlite_where=sa.text("status = 'active'"))
    op.drop_table('topics')
    op.drop_table('posting_modes')
    op.drop_table('digests')
    op.drop_table('users')
    # ### end Alembic commands ###
