"""add author metadata columns to source_posts

Revision ID: ed98306ffb75
Revises: 9bfe837aef51
Create Date: 2026-08-04 15:34:35.518608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed98306ffb75'
down_revision: Union[str, Sequence[str], None] = '9bfe837aef51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_posts', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.add_column('source_posts', sa.Column('following_count', sa.Integer(), nullable=True))
    op.add_column('source_posts', sa.Column('account_age_days', sa.Float(), nullable=True))
    op.add_column('source_posts', sa.Column('post_frequency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_posts', 'post_frequency')
    op.drop_column('source_posts', 'account_age_days')
    op.drop_column('source_posts', 'following_count')
    op.drop_column('source_posts', 'followers_count')
    # ### end Alembic commands ###
